batch_size: 32
data_dir: ../data/ai.hub
learning_rate: 1.0e-05
load_from_checkpoint: false
max_seq_len: 512
model_dir: ../data/ai.hub/checkpoints
model_file: ../data/ai.hub/checkpoints/kobert-ext-sum.ckpt
model_name: monologg/kobert
num_epochs: 100
top_k_sentences: 2
weight_decay: 0.01
