mode: extractive
default_root_dir: null
checkpoint_dir: ../../../src/data/cnn_daily/trained_models
learning_rate: 2.0e-05
min_epochs: 1
max_epochs: 100
min_steps: null
max_steps: 5000
accumulate_grad_batches: 1
check_val_every_n_epoch: 1
devices: auto
gradient_clip_val: 1.0
overfit_batches: 0.0
fast_dev_run: false
limit_train_batches: 1.0
limit_val_batches: 1.0
limit_test_batches: 1.0
amp_level: null
amp_backend: native
precision: 32
seed: null
profiler: null
progress_bar_refresh_rate: 50
num_sanity_val_steps: 2
val_check_interval: 1.0
use_logger: tensorboard
wandb_project: transformerextsum-private
gradient_checkpointing: false
accelerator: auto
do_train: true
do_test: false
load_weights: false
load_from_checkpoint: false
resume_from_checkpoint: null
use_custom_checkpoint_callback: true
custom_checkpoint_every_n: null
no_wandb_logger_log_model: false
auto_scale_batch_size: null
lr_find: false
adam_epsilon: 1.0e-08
optimizer_type: adam
ranger_k: 6
warmup_steps: 0
no_strict: true
use_scheduler: false
end_learning_rate: 2.0e-06
weight_decay: 0.01
plugins: null
logLevel: INFO
model_name_or_path: bert-base-uncased
model_type: bert
tokenizer_name: ''
tokenizer_no_use_fast: false
max_seq_length: 0
data_path: ../../../src/data/cnn_daily/cnn_dm/json.gz
data_type: txt
num_threads: 4
processing_num_threads: 2
pooling_mode: sent_rep_tokens
num_frozen_steps: 0
batch_size: 8
dataloader_type: map
dataloader_num_workers: 0
processor_no_bert_compatible_cls: true
only_preprocess: false
preprocess_resume: false
create_token_type_ids: binary
no_use_token_type_ids: false
classifier: simple_linear
classifier_dropout: 0.1
classifier_transformer_num_layers: 2
train_name: train
val_name: val
test_name: test
test_id_method: top_k
test_k: 3
no_test_block_trigrams: false
test_use_pyrouge: false
loss_key: loss_avg_seq_mean
